[build]
publish = "public"
command = "hugo"
[context.production]
command = "ln -s ${PWD} ../minimo && hugo --source=exampleSite --baseURL=${URL}"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[build.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
